version: 'cvautotrack.{build}'
os: Visual Studio 2017
configuration: Release
platform:
    - x64

environment:
  opencvinc: C:\project\opencv\include
  opencvlib: C:\project\opencv\x64\vc15\staticlib\lib
  opencvURL: https://github.com/GengGode/opencv450Release/releases/download/v1.0/Release.zip
  myProject: C:\project\cvAutoTrack\
  myProjectLib: C:\project\opencv\
skip_tags: true
  
install:
    - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()

    # download opencv:
    - mkdir %myProjectLib%
    - appveyor DownloadFile %opencvURL%
    - 7z x ./*.zip -y -o%myProjectLib%
    - rm -f ./*.zip

before_build: 
    - dir  %myProject%
    - dir  %myProjectLib%

build_script:
    - MSBuild C:\project\cvAutoTrack\cvAutoTrack.sln 

after_build:
    # copy include and source code files
    - mkdir %myProject%x64/build/
    - cp -r %myProject%x64/Release/*.dll %myProject%x64/build/

    - 7z a cvautotrack-%TIME_STRING%.7z %myProject%x64/build/*
    - appveyor PushArtifact cvautotrack-%TIME_STRING%.7z
    
#artifacts:
    #- path: build/Release
    #artifacts path name must be appveyor API
  
deploy:
    - provider: GitHub
      description: 'weekly build cvautotrack' 
      auth_token:
         secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
      draft: false
      tag: cvautotrack-%TIME_STRING%
      on:  
        APPVEYOR_REPO_TAG: false