name: genshintools
description: genshin tools
publish_to: 'none'
version: 2.4.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  dio: ^4.0.4
  flutter_markdown: ^0.6.8
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.7
  expandable: ^5.0.1
  flutter_services_binding: ^0.1.0
  uuid: ^3.0.5
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.0.17
  package_info_plus: ^1.3.0
  version: ^2.0.0
  webview_flutter: ^3.0.0
  filesize: ^2.0.1
  flutter_hooks: ^0.18.1
  rxdart: ^0.27.3
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  test: ^1.20.1
  analyzer: ^3.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  json_serializable: ^6.0.1
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/genshindb/