name: freearch
description: assets host in free service
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.1.0
  version: ^3.0.2
  roundtripper: ^0.4.0
  logr: ^0.1.5

dev_dependencies:
  dependency_validator: ^3.0.0
  build_runner: ^2.2.1
  test: ^1.20.1
  json_serializable: ^6.4.0
  freezed: ^2.1.1

