name: webdav
description: webdav client
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  freezed: ^2.0.3
  roundtripper: ^0.4.0
  logr: ^0.1.4

dev_dependencies:
  dependency_validator: ^3.0.0
  build_runner: ^2.1.5
  test: ^1.20.1
  json_serializable: ^6.0.1
  freezed: ^2.0.3+1
  contextdart: ^1.0.2

