name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_ID }}
          secret_key: ${{ secrets.COS_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ./sharedmap.user.js
          remote_path: /zhiqiong/sharedmap.user.js
          clean: false
